# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog by Hilzu
email: hilzu@iki.fi
description: >
  Random thoughts mostly about technology and especially about web stack.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.hilzu.moe" # the base hostname & protocol for your site
twitter_username: ze_hilda
github_username:  hilzu
permalink: pretty
# Build settings
markdown: kramdown

exclude: [vendor]

timezone: Europe/Helsinki
encoding: utf-8

gems:
  - jekyll-sitemap
